#!/bin/bash

clang \
    $@ \
    -std=c++11 \
    -lstdc++ \
    -lclangFrontendTool \
    -lclangFrontend \
    -lclangDriver \
    -lclangSerialization \
    -lclangCodeGen \
    -lclangParse  \
    -lclangSema \
    -lclangStaticAnalyzerFrontend \
    -lclangStaticAnalyzerCheckers \
    -lclangStaticAnalyzerCore \
    -lclangAnalysis \
    -lclangARCMigrate \
    -lclangRewrite \
    -lclangEdit \
    -lclangAST \
    -lclangLex \
    -lclangBasic \
    -lLLVM-5.0
