#!/usr/bin/env python3

import os
import sys

from argparse import ArgumentParser
from IPython.core.ultratb import VerboseTB

from lib.processor import CodeBase


def main():
    parser = ArgumentParser(description='Transform codebase to ClusterMP')
    parser.add_argument('-d', '--directory', action='store', help='The codebase to transform')
    args = parser.parse_args()

    os.chdir(args.directory)

    cb = CodeBase(args.directory)
    cb.parse()
    cb.transform()

    print(cb)
    # for file in cb.files:
    #     if file.tasks:
    #         print(file)


if __name__ == '__main__':
    #sys.excepthook = VerboseTB()
    main()
