#!/usr/bin/env python3

import os

from argparse import ArgumentParser

from lib.processor import CodeBase

def main():
    parser = ArgumentParser(description='Transform codebase to ClusterMP')
    parser.add_argument('-d', '--directory', action='store',
                        help='The codebase to transform')
    args = parser.parse_args()

    os.chdir(args.directory)

    cb = CodeBase(args.directory)
    cb.parse()

    print(cb)

if __name__ == '__main__':
    main()
